#pragma once

#include <JuceHeader.h>
#include <map>

namespace slicetribe
{

struct PresetData
{
    juce::String category, genre, name;
    bool factory = false;
    std::map<juce::String, float> values;   // parameter id → plain value
    juce::File file;                        // user presets only
};

/** Built-in presets (generated by tools/make_presets.py). Index 0 is "Init". */
const std::vector<PresetData>& factoryPresets();

/** Parameters stored in a preset (not Volume, Key or the New Loop trigger). */
const juce::StringArray& presetParameterIds();

/** Factory + user presets, loading, saving and "modified" tracking. Message thread only,
    except loadFactoryFromHost(), which a host may call from another thread. */
class PresetManager
{
public:
    explicit PresetManager (juce::AudioProcessorValueTreeState&);

    static juce::File getUserFolder();
    static juce::File fileForName (const juce::String& presetName);
    static constexpr const char* fileExtension = ".chupapreset";
    /** FX, fill and time feel are kept when a factory preset doesn't set them. */
    static bool isKeptParameter (const juce::String& id);

    void rescanUserPresets();
    int  getNumPresets() const;
    PresetData getPreset (int index) const;
    juce::StringArray getCategories() const;   // factory categories in order, then "User"

    void loadPreset (int index, bool fromHost = false);
    void loadFactoryFromHost (int factoryIndex);
    void loadNext (int direction);             // +1 / -1, wraps
    bool saveUserPreset (const juce::String& name, juce::String& error);
    bool deleteUserPreset (const juce::File&);
    juce::File importPresetFile (const juce::File&);   // copies into the user folder, returns the copy

    int  getCurrentIndex() const;
    juce::String getCurrentName() const;
    bool isModified() const;

    std::function<void (bool fromHost)> onPresetLoaded;   // e.g. to update the host's program display

    // project state
    void saveTo (juce::ValueTree& state) const;
    void restoreFrom (const juce::ValueTree& state);

private:
    void apply (const PresetData&);
    static std::map<juce::String, float> readPresetFile (const juce::File&, juce::String& nameOut, juce::String& categoryOut);

    juce::AudioProcessorValueTreeState& apvts;
    mutable juce::CriticalSection lock;
    std::vector<PresetData> userPresets;
    int currentIndex = 0;
    juce::String currentName { "Init" };
    std::map<juce::String, float> currentValues;   // values as loaded, for the modified flag
};

} // namespace slicetribe
